# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "i915" ];
  # acpi_call makes tlp work for newer thinkpads
  boot.kernelModules = [ "kvm-intel" "acpi_call "];
  boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];
  boot.resumeDevice = "/dev/disk/by-uuid/c9e733b6-b390-49f7-b1fb-54826c96fd92";
  boot.kernelParams = [ "resume_offset=2630912" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c9e733b6-b390-49f7-b1fb-54826c96fd92";
    fsType = "btrfs";
    options = [ "subvol=@" "noatime" "compress-force=zstd:1" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/238C-FE5D";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c9e733b6-b390-49f7-b1fb-54826c96fd92";
    fsType = "btrfs";
    options = [ "subvol=@home" "noatime" "compress-force=zstd:1" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/c9e733b6-b390-49f7-b1fb-54826c96fd92";
    fsType = "btrfs";
    options = [ "subvol=@nix" "noatime" "compress-force=zstd:1" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/c9e733b6-b390-49f7-b1fb-54826c96fd92";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@log" "noatime" "compress-force=zstd:1" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/c9e733b6-b390-49f7-b1fb-54826c96fd92";
    fsType = "btrfs";
    options = [ "subvol=@cache" "noatime" "compress-force=zstd:1" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/c9e733b6-b390-49f7-b1fb-54826c96fd92";
    fsType = "btrfs";
    options = [ "subvol=@tmp" "noatime" "compress-force=zstd:1" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/c9e733b6-b390-49f7-b1fb-54826c96fd92";
    options = [ "subvol=@snapshots" "noatime" "compress-force=zstd:1" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/c9e733b6-b390-49f7-b1fb-54826c96fd92";
    fsType = "btrfs";
    options = [ "subvol=@swap" "noatime" ];
  };

  fileSystems."/media/kingspec" = {
    device = "/dev/disk/by-uuid/82061815-5806-42cf-8c0f-d2e826d363e6";
    fsType = "ext4";
  };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
