# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/08f0d799-0d93-471f-b6b0-ddcd43ae0121";
    fsType = "btrfs";
    options = [ "subvol=@" "compress-force=zstd:1" "noatime" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A7D6-5852";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/08f0d799-0d93-471f-b6b0-ddcd43ae0121";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress-force=zstd:1" "noatime" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/08f0d799-0d93-471f-b6b0-ddcd43ae0121";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress-force=zstd:1" "noatime" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/08f0d799-0d93-471f-b6b0-ddcd43ae0121";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@log" "compress-force=zstd:1" "noatime" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/08f0d799-0d93-471f-b6b0-ddcd43ae0121";
    fsType = "btrfs";
    options = [ "subvol=@cache" "compress-force=zstd:1" "noatime" "discard=async" "space_cache=v2" "commit=120" ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/08f0d799-0d93-471f-b6b0-ddcd43ae0121";
    fsType = "btrfs";
    options = [ "subvol=@tmp" "compress-force=zstd:1" "noatime" "discard=async" "space_cache=v2" "commit=120" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
